### ISSUE TITLE
Allow changing of working dir, or respect `defaults.run.working-directory`

### ISSUE THREAD

**Issue by GregJohnStewart** [pavelzw/pytest-action#22]
Hello,

This seems to work, however, it does not respect the `defaults.run.working-directory` value set, and there is no way to specify the directory this should be run in. It only works for tests at the root level of the project, it seems.

It would be great to have both;

 - This action supports the `defaults.run.working-directory` value
 - Provide an option to run in a given directory

**Comment by uriafranko** [comment]
Hey @GregJohnStewart 
Adding `custom-pytest: 'cd app && poetry run pytest run_tests.py '` helped me fix this issue

**Comment by YuriiSSmolii** [comment]
Same issue, I have to specify the path to the folder with specific tests, but there is no such option..

**Comment by ostov** [comment]
```
      - name: 'Test: Run'
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          custom-pytest: 'cd webhook-billing-record && python3 -m pytest'
          custom-arguments: 'tests/*'
          click-to-expand: true
          report-title: 'Test Report'
```
But I agree that this ^^^ is not obvious at first sight and option to run in a given directory would be grate!
