### ISSUE TITLE
error: unrecognized arguments: --md=/tmp/tmp.tZ5EFsP32C

### ISSUE THREAD

**Issue by bmos** [pavelzw/pytest-action#23]
In [this Action](https://github.com/MaineDSA/membership_dashboard/blob/e5abaa280570635c1bf1c2846696e70c501e1ff3/.github/workflows/pytest.yml):
```yml
name: Run Pytest

on: [push]

jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.12", "3.11", "3.10", "3.9"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pytest pytest-emoji
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi

    - name: Test code with pytest
      uses: pavelzw/pytest-action@v2
      with:
        emoji: true
        verbose: false
        job-summary: true
```

I ran into [this error](https://github.com/MaineDSA/membership_dashboard/actions/runs/7352152361/job/20016491554#step:5:35):
```
Run pavelzw/pytest-action@v2
  with:
    emoji: true
    verbose: false
    job-summary: true
    custom-pytest: pytest
    report-title: Test Report
    click-to-expand: true
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.7/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.7/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.7/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.7/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.7/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.7/x64/lib
Run REPORT="$(mktemp)"
  REPORT="$(mktemp)"
  echo "report-path=$REPORT" >> $GITHUB_OUTPUT
  pytest --md=$REPORT --emoji
  shell: /usr/bin/bash -el {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.7/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.7/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.7/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.7/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.7/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.7/x64/lib
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --md=/tmp/tmp.tZ5EFsP32C
  inifile: None
  rootdir: /home/runner/work/membership_dashboard/membership_dashboard

Error: Process completed with exit code 4.
```

Am I doing something wrong? I switched to just using a simple run Action and it's working but I like the summaries from your Action.

**Comment by pavelzw** [comment]
This actually looks like something that _might_ be fixed by #20 😅 

Can you try out if the following works?

```yml
    - name: Test code with pytest
      uses: pavelzw/pytest-action@quote-report
      with:
        emoji: true
        verbose: false
        job-summary: true
```
